remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [tck_jca_v2_1]
description: [Eclipse Technology Compatibility Kit User's Guide for Jakarta EE Connector 2.1 for
                Technology
                Licensees, Release 2.1]

# sidebar links url
links:
  source: https://github.com/eclipse-ee4j/jakartaee-tck
  download: https://jakarta.ee/specifications/connectors/2.1/
  #mailinglist: jca-dev@eclipse.org
  #javadocs:
  docs: https://jakarta.ee/specifications/connectors/2.1/apidocs/
  #faq:

